const formDB = [
  {
    title: "Имя",
    name: "name",
    placeholder: "Иван",
    type: "text",
    isValid: true,
    errorMessage: "",
    multiInput: false,
  },
  {
    title: "Фамилия",
    name: "surname",
    placeholder: "Иванов",
    type: "text",
    isValid: true,
    errorMessage: "",
    multiInput: false,
  },
  {
    title: "Дата рождения",
    name: "birthday",
    placeholder: "",
    type: "date",
    isValid: true,
    errorMessage: "",
    multiInput: false,
  },
  {
    title: "Телефон",
    name: "phone",
    placeholder: "7-7777-77-77",
    type: "tel",
    isValid: true,
    errorMessage: "",
    multiInput: false,
  },
  {
    title: "Сайт",
    name: "website",
    placeholder: "https://mysite.com",
    type: "text",
    isValid: true,
    errorMessage: "",
    multiInput: false,
  },
  {
    title: "О себе",
    name: "about",
    placeholder: "Я Frontend разработчик...",
    type: "text",
    isValid: true,
    errorMessage: "",
    multiInput: true,
  },
  {
    title: "Стек технологий",
    name: "techstack",
    placeholder: "JavaScript...",
    type: "text",
    isValid: true,
    errorMessage: "",
    multiInput: true,
  },
  {
    title: "Описание последнего проекта",
    name: "lastProject",
    placeholder: "Мы сделали...",
    type: "text",
    isValid: true,
    errorMessage: "",
    multiInput: true,
  },
];
export default formDB;
